### ISSUE TITLE
Any body help me? 有人能帮我吗？

### ISSUE THREAD

**Issue by Darling-Lee** [Anjok07/ultimatevocalremovergui#1013]
My machine info:我的设备信息：
Intel MacOS 12.7.1

launch UVR fail, the error message is follow:启动UVR失败，下面是错误信息：
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 1878, in <module>
  File "numba/core/decorators.py", line 234, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[906] Failed to execute script 'UVR' due to unhandled exception: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[906] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/utils.py", line 1878, in <module>
  File "numba/core/decorators.py", line 234, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'

HOW CAN I DO?我该如何做？

**Comment by Darling-Lee** [comment]
> Did you read this in the README here? "**MacOS Users: Having Trouble Opening UVR**" Also, you could try to update the Python manually to 3.10 or higher: https://www.python.org/downloads/macos/

Thank you for your response. Yes, I even tried resigning UVR and installing Python 3.10, 3.11, and 3.12, but the issue still persists.
