### ISSUE TITLE
Unable to open on Mac, OS Big Sur

### ISSUE THREAD

**Issue by Syntoca** [Anjok07/ultimatevocalremovergui#1019]
Program cannot open, running into this issue as seen on the command line:

\# /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR 
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 78, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/files.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/__init__.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/processors.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "lzma.py", line 27, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so
  Reason: Incompatible library version: _lzma.cpython-311-darwin.so requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
[1635] Failed to execute script 'UVR' due to unhandled exception: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so
  Reason: Incompatible library version: _lzma.cpython-311-darwin.so requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
[1635] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/__init__.py", line 78, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "librosa/util/files.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/__init__.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "pooch/processors.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "lzma.py", line 27, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_lzma.cpython-311-darwin.so
  Reason: Incompatible library version: _lzma.cpython-311-darwin.so requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0

Would this be an issue with my version of Python, or with my computer for whatever reason?

**Comment by abjaeger** [comment]
Same problem here - hoping for a solution soon
