### ISSUE TITLE
[INSTALLATION PROBLEM] Cannot run VocalRemover.py no matter what I've tried

### ISSUE THREAD

**Issue by Benjammin-n215** [Anjok07/ultimatevocalremovergui#113]
**First off: I've no experience with python and coding, so I only vaguely understand what's going on here.**
### **To Reproduce**
-Opening VocalRemover.py failed. Produced a large string of text then closed too fast to read.
-Running '_python VocalRemover.py_' with both python.exe and python3.exe OR just python.exe as the execution alias produces the following:

> Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

-Running '_python VocalRemover.py_' with only python3.exe as the execution alias produces the following: 

> Traceback (most recent call last):
>   File "VocalRemover.py", line 25, in <module>
>     import inference_v2
>   File "C:\Users\Shino\Documents\UVR-V4GUI\inference_v2.py", line 5, in <module>
>     import librosa
>   File "C:\Users\Shino\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\__init__.py", line 14, in <module>
>     from . import decompose
>   File "C:\Users\Shino\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\decompose.py", line 19, in <module>
>     import sklearn.decomposition
>   File "C:\Users\Shino\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\__init__.py", line 81, in <module>
>     from . import __check_build  # noqa: F401
> ImportError: cannot import name '__check_build' from 'sklearn' (C:\Users\Shino\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\__init__.py)
> PS C:\Users\Shino\Documents\UVR-V4GUI>

![python error](https://user-images.githubusercontent.com/91659158/135411055-68d32a83-13e2-4a6d-9fff-18991d0336d1.png)

### **Desktop**
 - OS: Windows 10

### **Context**
-I attempted to install Scipy and reinstall Sklearn and Scikit.
-The following would not finish correctly until I did the above.

> pip install --no-cache-dir -r requirements.txt
> pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

I've tried reinstalling python with the PATHS box checked.
![PATHS](https://user-images.githubusercontent.com/91659158/135411846-44f4eec2-a896-4129-9296-4a6634a403ad.png)

**Comment by Benjammin-n215** [comment]
Figured out how to fix the issue, turns out I was missing opencv and librosa
