### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by eldomtom2** [Anjok07/ultimatevocalremovergui#1134]
I get this error when trying to install on Pop!_OS:

Traceback (most recent call last):
  File "/mnt/ed6dcccf-6940-428b-83b2-0ab4b050e908/Hard Drive Documents/ultimatevocalremovergui-master/UVR.py", line 8, in <module>
    import librosa
  File "/home/tom/.local/lib/python3.10/site-packages/librosa/__init__.py", line 211, in <module>
    from . import decompose
  File "/home/tom/.local/lib/python3.10/site-packages/librosa/decompose.py", line 19, in <module>
    import sklearn.decomposition
ModuleNotFoundError: No module named 'sklearn'

**Comment by eldomtom2** [comment]
For some reason this has now resolved itself.
