### ISSUE TITLE
Failed to execute script 'UVR' due to unhandled exception

### ISSUE THREAD

**Issue by SCSR-is-too-short-username** [Anjok07/ultimatevocalremovergui#1170]
After updating to the newest version I'm getting the following error when trying to run the program:
`Failed to execute script 'UVR' due to unhandled exception: cannot import name '_get_cpp_backtrace' from 'torch._C' (D:\Ultilate Vocal Remover\Ultilate Vocal Remover\torch\_C.px39-win_amd64.pyd)`

```
Traceback (most recent call last):
  File "UVR.py", line 21, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\__init__.py", line 649, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\_tensor.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\utils\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\utils\cpp_backtrace.py", line 1, in <module>
ImportError: cannot import name '_get_cpp_backtrace' from 'torch._C' (D:\Ultimate Vocal Remover\Ultimate Vocal Remover\torch\_C.cp39-win_amd64.pyd)
```

I updated by downloading the patch on the releases page. I am running Windows 10 on Intel CPU. I am a bit confused why the .pyd file says "amd". Could that be the issue?

**Comment by kchanLuo** [comment]
Hello, I have the same problem with you, have you solved it？
