### ISSUE TITLE
WinError 126

### ISSUE THREAD

**Issue by ENunn** [Anjok07/ultimatevocalremovergui#127]
Trying to run some models on a clean Win11 install, I'm getting an error. All I did was follow the steps [here](https://github.com/Anjok07/ultimatevocalremovergui/blob/v5-beta-cml/README.md#installation), so I don't know what I did wrong.
```

Traceback (most recent call last):
  File "ensemble_inference.py", line 5, in <module>
    import librosa
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\spide\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 64, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Any fix?

**Comment by ENunn** [comment]
i fixed this error by reinstalling python, but now i'm getting even more errors and i don't know how to fix them.

[Running and Ensembling HP2 Instrumental Models
loading model... done
loading & stft of wave source... Traceback (most recent call last):
  File "inference.py", line 344, in <module>
    main()
  File "inference.py", line 181, in main
    wave = librosa.resample(wave, mp.param['band'][d+1]['sr'], bp['sr'], res_type=bp['res_type'])
  File "C:\Python37\lib\site-packages\librosa\core\audio.py", line 524, in resample
    util.valid_audio(y, mono=False)
  File "C:\Python37\lib\site-packages\librosa\util\utils.py", line 278, in valid_audio
    raise ParameterError('Audio buffer is not Fortran-contiguous. '
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.
loading model... done
loading & stft of wave source... Traceback (most recent call last):
  File "inference.py", line 344, in <module>
    main()
  File "inference.py", line 181, in main
    wave = librosa.resample(wave, mp.param['band'][d+1]['sr'], bp['sr'], res_type=bp['res_type'])
  File "C:\Python37\lib\site-packages\librosa\core\audio.py", line 524, in resample
    util.valid_audio(y, mono=False)
  File "C:\Python37\lib\site-packages\librosa\util\utils.py", line 278, in valid_audio
    raise ParameterError('Audio buffer is not Fortran-contiguous. '
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.
Ensembling...: 0it [00:00, ?it/s]usage: spec_utils.py [-h]
                     [--algorithm {invert,invert_p,min_mag,max_mag,deep,align}]
                     [--model_params MODEL_PARAMS] [--output_name OUTPUT_NAME]
                     [--vocals_only]
                     input [input ...]
spec_utils.py: error: the following arguments are required: input
Ensembling...: 1it [00:01,  1.53s/it]usage: spec_utils.py [-h]
                     [--algorithm {invert,invert_p,min_mag,max_mag,deep,align}]
                     [--model_params MODEL_PARAMS] [--output_name OUTPUT_NAME]
                     [--vocals_only]
                     input [input ...]
spec_utils.py: error: the following arguments are required: input
Ensembling...: 2it [00:03,  1.53s/it]
Traceback (most recent call last):
  File "ensemble_inference.py", line 247, in <module>
    main()
  File "ensemble_inference.py", line 217, in main
    os.path.join('separated', f"{basename}_{pm}_Instruments.wav")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'ensembled\\temp\\musicaots51606-1_HP2-4BAND-3090_4band_1_Instruments.wav' -> 'separated\\musicaots51606-1_HP2-4BAND-3090_4band_1_Instruments.wav'](url)

please help me, i don't know what to do. i don't know what i did wrong. it worked perfectly fine before i did a clean install of windows.

**Comment by aufr33** [comment]
What is your librosa version?

**Comment by ENunn** [comment]
it's the latest, 0.8.1.

i do have an older version of the v5 batch files and python scripts that i downloaded in october, i have no errors at all.

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
