### ISSUE TITLE
[INSTALLATION PROBLEM] ''MGM-v5-KAROKEE-32000-BETA2-AGR''

### ISSUE THREAD

**Issue by iNielsG** [Anjok07/ultimatevocalremovergui#135]
I use the batch file: ''Drag-n-Drop-CHOOSE-YOUR-MODEL.bat'' to make a karaoke. Everytime I tried to use the Beta2-agr I got an error: 

''Running Model MGM-v5-KAROKEE-32000-BETA2-AGR
loading model... Traceback (most recent call last):
  File "inference.py", line 344, in <module>
    main()
  File "inference.py", line 140, in main
    model.load_state_dict(torch.load(args.pretrained_model, map_location=device))
  File "C:\Users\Gielingh\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 586, in load
    if _is_torchscript_zip(opened_zipfile):
  File "C:\Users\Gielingh\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 859, in _is_torchscript_zip
    return 'constants.pkl' in zip_file.get_all_records()
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:211] . file in archive is not in a subdirectory archive/: param.json''

Any solutions?

**Comment by aufr33** [comment]
Fix: https://github.com/Anjok07/ultimatevocalremovergui/issues/63#issuecomment-829858503
