### ISSUE TITLE
Deprecated component in use "sklearn" + "GLU library not found"

### ISSUE THREAD

**Issue by TechNerd-019** [Anjok07/ultimatevocalremovergui#1452]
System: Ubuntu 22.04 (Running through DistroBox)
Host System: Fedora Workstation 40, GNOME 46.3.1
Kernel: 6.9.7-200.fc40.x86_64
CPU: Core i7-11800H Mobile CPU
GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q

I have downloaded the repository master file from the given link on the Linux instructions section. Upon execution of the command "pip3 install -r requirements.txt", the following error is produced:

```Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Collecting numpy==1.23.5
```

I am not much of a Python programmer, but it sounds like a package that is deprecated is trying to get installed. I am aware you can set a deprecation warning filter that could mitigate this problem, but since the error comes from a setup.py file that is not accessible from the downloaded zip, I have no way of modifying it.

I installed each package by manually running the SH script, and after attempting to execute UVR.py, I get an error saying that the GLU library is not found.

```
📦[technerd@ubuntubox ultimatevocalremovergui-master]$ python3 UVR.py
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/technerd/Documents/UVR/ultimatevocalremovergui-master/UVR.py", line 7257, in <module>
    root = MainWindow()
  File "/home/technerd/Documents/UVR/ultimatevocalremovergui-master/UVR.py", line 1291, in __init__
    self.set_app_font()
  File "/home/technerd/Documents/UVR/ultimatevocalremovergui-master/UVR.py", line 1559, in set_app_font
    pyglet_font.add_file(FONT_MAPPER[MAIN_FONT_NAME])
  File "/usr/local/lib/python3.10/dist-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/usr/local/lib/python3.10/dist-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/usr/local/lib/python3.10/dist-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/usr/local/lib/python3.10/dist-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/usr/local/lib/python3.10/dist-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.
```

This may very well be because of the SKLearn issue, but I was not sure, so decided to include it either way.

**Comment by CyberT33N** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/issues/1435#issuecomment-2198422162

**Comment by zdd123456M** [comment]
Update Ultimate Vocal Remover UVR5 version as soon as possible

**Comment by zdd123456M** [comment]
Update Ultimate Vocal Remover UVR5 version as soon as possible
