### ISSUE TITLE
Failed to esecute script 'UVR' due to unhandled exception: invalid load key, '\100'

### ISSUE THREAD

**Issue by Miaka82** [Anjok07/ultimatevocalremovergui#1455]
Buongiorno, ho utilizzato il programma con successo fino a stamattina, quando ha cominciato a bloccarsi e bloccare tutto il sistema del mio pc. Stavo utilizzando queste impostazioni:
MP3
Ensemble mode
Multi-stem ensemble
Max Spec
GPU conversion
MDX-Net UVR MDX-NET Inst HQ 3
Demucs v4 | htdemucs

Prima ha smesso di salvare i file htdemucs (others,drums, bass...) e salvava solo gli HQ (instrumental e vocals); poi non ha salvato più neanche quelli.
Ho provato a disinstallare e reinstallare, ma niente. Poi ho scaricato e installato nuovamente UVR5, nella versione 5.6.0, ma il problema è rimasto. Sono riuscita a fare una prova, aggiungendo anche i file HP UVR e DeNoise, ha salvato solo quelli, e poi ha bloccato di nuovo tutto il pc.

Adesso se provo ad aprire il programma scrive questo: 
Failed to esecute script 'UVR' due to unhandled exception: invalid load key, '\100'

E sotto questo:
Traceback (most recent call last):
  File "UVR.py", line 288, in <module>
  File "UVR.py", line 181, in load_data
_pickle.UnpicklingError: invalid load key, '\x00'.

Cosa devo fare per risolvere il problema?
Grazie

**Comment by Miaka82** [comment]
Ho risolto da sola, grazie lo stesso!
