### ISSUE TITLE
Error When Launching UVR5

### ISSUE THREAD

**Issue by Spooner-wav** [Anjok07/ultimatevocalremovergui#1468]
When i try to lauch UVR5, both from the launcher and the application file i get this error:

Failed to execute script 'UVR' due to unhandled exception: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\jjcoo\AppData\Local\Programs Ultimate Vocal Remover\torch\lib\shm.dlI" or one of its dependencies.

Traceback (most recent call last):
File "UVR.py", line 21, in < module>
File "< frozen importlib._bootstrap>", line 1007, in _find_and_load File "< frozen importlib. _bootstrap>", line 986, in _find_and_load _unlocked File "< frozen importlib._bootstrap»", line 680, in _load _unlocked File "Pylnstaller\loader\pyimod03_importers.py", line 495, in exec_module
File "torchL_init_•py", line 128, in < module>
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C.Users\jjcoo\AppData\Local\Programs\Ultimate Vocal Remover\torch\ lib\shm.dil" or one of its dependencies.

Any help is greatly appreciated as i would really like to use UVR5!

**Comment by D3rel** [comment]
The same thing is happening to me after updating with the latest version **UVR_Patch_10_6_23_4_27.exe**:

Traceback (most recent call last):
  File "UVR.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\__init__.py", line 231, in <module>
TypeError: can't set attributes of built-in/extension type 'torch._C.DisableTorchFunctionSubclass'

**Comment by tedy02** [comment]
I'm getting:

Traceback (most recent call last):
  File "UVR.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\__init__.py", line 128, in <module>
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\theod\AppData\Local\Programs\Ultimate Vocal Remover\torch\lib\cufft64_10.dll" or one of its dependencies.

anyone ever figure this out? I uninstalled and reinstalled receving the same error both times the application tries to load.

**Comment by o-bardiuk** [comment]
> OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\theod\AppData\Local\Programs\Ultimate Vocal Remover\torch\lib\cufft64_10.dll" or one of its dependencies.

I had the same error. I had Python 10 installed, which might have messed up the PATH or something. Try uninstalling it. UVR5 is a self-contained package. I did it and it is working now.
