### ISSUE TITLE
UVR v5.6 on macOS 12.7.4 - app closes right after starting due to case-sensitive font name file 

### ISSUE THREAD

**Issue by notkelvin** [Anjok07/ultimatevocalremovergui#1601]
Hello,

I ran into an issue with UVR v5.6 on macOS 12.7.4.  I downloaded from the .dmg file "Ultimate_Vocal_Remover_v5_6_MacOS_x86_64.dmg" from the GitHub page and put it in my /Application dir.  Then I did the steps to let macOS run it while bypassing the verification (disabled it for the app via Security & Privacy page) -- so far so good, but when I try to open the app, it appears in the dock for a few seconds and disappears.

I found out that the issue is one of the filenames in the app is different from what the app expects by opening Terminal and tried to run the binary manually, I got the error:

```
pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
torch/_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x13b79e160>.
  warnings.warn(
torch/_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x13b7b0cc0>.
  warnings.warn(
2024-10-26 22:44:16.472 UVR[34955:14164269] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/_1/rp2drch16pjf93x0d979m2vr0000gn/T/UVR.savedState
Traceback (most recent call last):
  File "UVR.py", line 7200, in <module>
  File "UVR.py", line 1276, in __init__
  File "UVR.py", line 1542, in set_app_font
  File "pyglet/font/__init__.py", line 183, in add_file
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/gui_data/fonts/centurygothic/GOTHIC.ttf'
[34955] Failed to execute script 'UVR' due to unhandled exception: [Errno 2] No such file or directory: '/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/gui_data/fonts/centurygothic/GOTHIC.ttf'
[34955] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 7200, in <module>
  File "UVR.py", line 1276, in __init__
  File "UVR.py", line 1542, in set_app_font
  File "pyglet/font/__init__.py", line 183, in add_file
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/gui_data/fonts/centurygothic/GOTHIC.ttf'
```

I noticed in `/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/gui_data/fonts/centurygothic/`, the file is named `GOTHIC.TTF`.  

I created a symlink to that file at `/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/gui_data/fonts/centurygothic/GOTHIC.ttf` and UVR started working fine after.

**Comment by Anjok07** [comment]
Thank you for bringing this to my attention! I will ensure this is addressed in the next version
