### ISSUE TITLE
Problem installation (python version)

### ISSUE THREAD

**Issue by Dokjolly0** [Anjok07/ultimatevocalremovergui#1628]
What python version i need to install requirement (v5.6)?

now i catch this error (arc linux):
(env) [Dokjolly@arch ultimatevocalremovergui-5.6]$ pip install -r requirements.txt
Ignoring SoundFile: markers 'sys_platform == "windows"' don't match your environment
Collecting altgraph==0.17.3 (from -r requirements.txt (line 1))
  Downloading altgraph-0.17.3-py2.py3-none-any.whl.metadata (7.4 kB)
Collecting audioread==3.0.0 (from -r requirements.txt (line 2))
  Downloading audioread-3.0.0.tar.gz (377 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/Dokjolly/Desktop/ultimatevocalremovergui-5.6/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/Dokjolly/Desktop/ultimatevocalremovergui-5.6/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/Dokjolly/Desktop/ultimatevocalremovergui-5.6/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-nyx53dey/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-nyx53dey/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nyx53dey/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-nyx53dey/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ANTIAN-STAR** [comment]
The error you're encountering seems to be related to the fact that imp (a deprecated module in Python 3.12) is being used somewhere in the package you're trying to install. Specifically, the error message indicates:

ModuleNotFoundError: No module named 'imp'
This suggests that the package you're trying to install (likely audioread or a dependency thereof) is using the old imp module, which was removed in Python 3.12.

Solution:
Python Version Compatibility: The package you're trying to install may not yet support Python 3.12, which is likely the root cause. The imp module was deprecated in Python 3.4 and removed in Python 3.12. It’s possible that audioread or one of its dependencies needs to be updated to support Python 3.12.

The error you are seeing is likely because the code is attempting to use the deprecated imp module, which worked in older Python versions but has been fully removed in Python 3.12.

Solution: Downgrade your Python version to 3.10 or 3.11.

Python 3.10 and 3.11 should work fine with the libraries you're trying to install. Here's how you can do it on Arch Linux:

Install Python 3.10 or 3.11:

You can install a specific version of Python using pyenv, a version management tool for Python, which allows you to manage multiple Python versions on your system.

First, install pyenv if you haven't already:

sudo pacman -S pyenv
Then, install Python 3.10 or 3.11:

pyenv install 3.10.10  # Or use 3.11.x if you prefer
pyenv global 3.10.10   # Set it as the global Python version
After switching to Python 3.10 or 3.11, recreate your virtual environment and try installing the requirements again.

python -m venv env  # Create a new virtual environment
source env/bin/activate  # Activate the environment
pip install -r requirements.txt  # Install dependencies
Workaround for Python 3.12: If you absolutely need to stay with Python 3.12, you can try modifying the audioread package or its dependencies to avoid using the deprecated imp module. However, this is more complex and may require patching the source code of the package, which is generally not recommended unless you're familiar with the codebase.

You could also check if there is an updated version of audioread or other dependencies that support Python 3.12. Sometimes, updating the dependencies in requirements.txt might help:

pip install --upgrade audioread
Upgrade pip: Your pip version is slightly out of date. It may be a good idea to upgrade it to avoid any potential issues with dependency installation. You can upgrade pip using:

pip install --upgrade pip
Summary:
Primary fix: Downgrade Python to 3.10 or 3.11, as Python 3.12 removes the imp module that some dependencies are still using.
Alternative: Upgrade dependencies (if available) to support Python 3.12, or patch the code yourself (not recommended unless you're familiar with the source code).
Let me know if you need further clarification or help with any of the steps!

**Comment by NthTry99** [comment]
I'm also running Arch Linux and I had the exact same problem, the center of the problem seemed to be the "ModuleNotFoundError: No module named 'imp'"
After MUCH Googling, here's what I found and what I did to get UVR v5.6 to work.

It has to do with the fact that the last time UVR was updated, Python 3.11 was the latest version of Python and used this 'imp' module, which was deprecated and replaced with 'importlib' in Python 3.12 (the current version). I am not a programmer but I tried everything to replace everywhere I could find in the UVR files where "import imp" was and replace it with "import importlib" but still got the same error. So I installed python311 (aka Python 3.11) from the AUR:

$ yay -S python311
This will install Python 3.11 independently of any other version of Python you might already have installed (iirc).

Here's exactly my steps, beginning after unzipping "ultimatevocalremovergui-master.zip" to ./ultimatevocalremovergui-master and cd'ing into that directory:

This creates a venv (virtual environment) using Python 3.11. I believe using a venv is important, as you will see later.
$ python3.11 -m venv ./venv

If I didn't include this, I would get a different error pertaining to "OSError: could not get source code", this fixed that:
$ venv/bin/pip3.11 install --upgrade setuptools wheel

Then, I kept getting another error about another deprecated package:
"The 'sklearn' PyPI package is deprecated, use 'scikit-learn' rather than 'sklearn' for pip commands."

To fix this, I had to set an environment variable to be used in the venv:
$ nano ./venv/bin/activate

Directly under "deactivate () {" add (without quotes): "unset SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL": so it should look like:
`deactivate () {`
`unset SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL`
This will unset the environment variable once you deactivate the venv ($ deactivate) which I do when I am done using UVR.

Then while still in nano editing ./venv/bin/activate at the very bottom add the line: 
`export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL="True"`

Now you can install the requirements.txt:
$ venv/bin/pip3.11 install -r requirements.txt
(I think you must use pip3.11 because it specifies Python 3.11)

To run UVR, activate the venv:
$ source ./venv/bin/activate

And execute the .py:
$ python3.11 UVR.py
(again I'm pretty sure you have to use python3.11 in the above command or else it will use 3.12 if you have that installed.

I will probably end up coming back here to refine this post, I'm new here lol but I hope this works for you too!

**Comment by RustoMCSpit** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/issues/1674

ive managed to get it working here
