### ISSUE TITLE
Linux installation Error....

### ISSUE THREAD

**Issue by CodesoundR** [Anjok07/ultimatevocalremovergui#1661]
Linux Mint 22_x64 Cinnamom

Hi,
I try to install ultimatevocalremover into my sistem following "Linux Installation (Updated Instructions)" but one step is missing: 

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.12-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /media/codesound/DATA/SOFTWARE/AI/UltimateVocalRemover/ultimatevocalremovergui-master/venv/bin/python3

in the list provided, the seguent command is missing:
sudo apt install python3.12-venv

but the install don't finish correctly:

pip install -r requirements.txt
Ignoring PySoundFile: markers 'sys_platform == "darwin"' don't match your environment
Collecting altgraph==0.17.3 (from -r requirements.txt (line 1))
  Downloading altgraph-0.17.3-py2.py3-none-any.whl.metadata (7.4 kB)
Collecting audioread==3.0.0 (from -r requirements.txt (line 2))
  Downloading audioread-3.0.0.tar.gz (377 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.0/377.0 kB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/media/codesound/DATA/SOFTWARE/AI/UltimateVocalRemover/ultimatevocalremovergui-master/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/media/codesound/DATA/SOFTWARE/AI/UltimateVocalRemover/ultimatevocalremovergui-master/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/media/codesound/DATA/SOFTWARE/AI/UltimateVocalRemover/ultimatevocalremovergui-master/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9yph02p2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-9yph02p2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-9yph02p2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-9yph02p2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

please, how can I fix this error?

regards

**Comment by tdrebes** [comment]
Seems like imp was removed in python 3.12.
Try python 3.10 or 3.11 and it should work.

**Comment by CodesoundR** [comment]
> Seems like imp was removed in python 3.12. Try python 3.10 or 3.11 and it should work.

Hi,
Thank you for your reply! I try to install your suggestions, but I'm not lucky: maybe I'm doing something wrong?

codesound@worker:~$ sudo apt install python3.11-venv
[sudo] password for codesound:           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.11-venv
E: Couldn't find any package by glob 'python3.11-venv'
codesound@worker:~$ sudo apt install python3.10-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.10-venv
E: Couldn't find any package by glob 'python3.10-venv'
codesound@worker:~$ sudo apt install python3.11
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.11
E: Couldn't find any package by glob 'python3.11'
codesound@worker:~$ sudo apt install python3.10
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.10
E: Couldn't find any package by glob 'python3.10'
codesound@worker:~$ 

regards

**Comment by tdrebes** [comment]
The apt repository most likely only provides python 3.12. Also shouldn't replace that if Mint depends on it.
You can use something like pyenv or conda to install and run python 3.10 alongside 3.12.

**Comment by RustoMCSpit** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/issues/1674

ive managed to get it working here

**Comment by nyh** [comment]
> Seems like imp was removed in python 3.12. Try python 3.10 or 3.11 and it should work.

Half a year later, this seems even less like a good solution. My system (Fedora 41) has Python 3.13.2, and although Fedora does have a "python3.11" package which one can install to get a second, old, version of Python, this is not a desirable solution. The real solution is for modern software to _also_ be able to run on modern tools and not require older versions.
