### ISSUE TITLE
Linux Mint Installation Problems

### ISSUE THREAD

**Issue by RustoMCSpit** [Anjok07/ultimatevocalremovergui#1674]
```
pip3 install -r requirements.txt
Ignoring PySoundFile: markers 'sys_platform == "darwin"' don't match your environment
Requirement already satisfied: altgraph==0.17.3 in ./uvr-env/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (0.17.3)
Collecting audioread==3.0.0 (from -r requirements.txt (line 2))
  Using cached audioread-3.0.0.tar.gz (377 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/desktoppc/Desktop/UVR/ultimatevocalremovergui-master/uvr-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/desktoppc/Desktop/UVR/ultimatevocalremovergui-master/uvr-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/desktoppc/Desktop/UVR/ultimatevocalremovergui-master/uvr-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b8hiafnw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b8hiafnw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-b8hiafnw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-b8hiafnw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by RustoMCSpit** [comment]
ModuleNotFoundError: No module named 'imp'

you have to use a python environment that is 3.11.11.
3.12 or above breaks this.

the packages being used here are largely deprecated, this project needs a bit of a clean up no offense!

**Comment by RustoMCSpit** [comment]
UVR5 runs off extremely old dependencies so you need to to download an older version of python that's even capable of running those dependencies.

this guide works for Linux Mint Cinnamon. If you use something besides Debian (and its native package installer apt) or one of its derivatives, you will need to change the below a bit

check your python version, it needs to be 3.11.11

```
python3 --version
```

(if youre not on it, you can check if you have it installed but not on but you most likely certainly dont unless youve intentionally done that)

otherwise, you need to install 3.11.11 through deadsnakes

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
```

then (python dev is neeed even though the readme doesnt say so, or the requirements)

```
sudo apt-get install python3.11 python3.11-venv python3.11-dev
```

if you do not have pip installed already, do that too
```
sudo apt install pip
```

make a 3.11.11 environment

```
python3.11 -m venv NAMEOFENVIRONMENT
```

then you need to enter your environment

```
source NAMEOFENVIRONMENT/bin/activate
```

 you also need to manually install all the addons inside a venv envionment. heres a command to do that:

```
pip install altgraph==0.17.3 audioread==3.0.0 certifi==2022.12.07 cffi==1.15.1 cryptography==3.4.6 einops==0.6.0 future==0.18.3 julius==0.2.7 kthread==0.2.3 librosa==0.9.2 llvmlite matchering==2.0.6 ml_collections==0.1.1 natsort==8.2.0 omegaconf==2.2.3 opencv-python==4.6.0.66 Pillow==9.3.0 psutil==5.9.4 pydub==0.25.1 pyglet==1.5.23 pyperclip==1.8.2 pyrubberband==0.3.0 pytorch_lightning==2.0.0 PyYAML==6.0 resampy==0.4.2 scipy==1.9.3 soundstretch==1.2 torch urllib3==1.26.12 wget==3.2 samplerate==0.1.0 screeninfo==0.8.1 diffq playsound==1.2.2 onnx onnxruntime onnxruntime-gpu onnx2pytorch SoundFile==0.11.0; sys_platform != 'darwin' PySoundFile==0.9.0.post1; sys_platform == 'darwin' numpy==1.23.5
```

for every file that doesnt work you need to go here and download a zip of the correct version listed in the requirements text (and if a version isnt listed just get the newest one or the one closest to late 2023 as that was when this was last compiled) https://pypi.org/

once you install the compressed file, just do

```
pip install NAMEOFFILE
```

also, sklearn isnt even functioning anymore, ive no idea why it's listed as a requirement in 2025 (outdated project but still). use scikit-learn. 

(i went into the command and removed the line Dora==0.0.3 as this is the package that's calling sklearn. Ironically, it isn't needed at all since the only instance of it being called was in a file called pretrained.py, but even then it's commented out. that means scikit-learn also isnt needed, but id rather just install it in case of future updates.)

```
pip install scikit-learn
```

you also need tkinter and tqdm, another two dependencies not listed by the readme

```
sudo apt-get install python3.11-tk
```

then

```
pip install tqdm
```

you can then try python3 UVR.py (your terminal needs to be in the directory where thats located).

```
python3 UVR.py
```
(try "python UVR.py" if that doesnt work)

keep trying to run with "python3 UVR.py" and install any dependency or whatever you need to.

you might not be able to use GPU mode, you might have to have a NVIDIA GPU im not sure. regardless, CPU mode in a native linux install is far faster than in the windows wine version. for me it's 15x-20x more fast.

you will need to open this everytime with the following terminal command

```
source NAMEOFENVIRONMENT/bin/activate && python3 UVR.py
```

i have not covered methods of making memory more available for python processes (you can use some flags in the command, close apps, etc.) or how to make a command into a shell script you can click on like an app icon.

after you get this app, you need to get this app if you want to do ai voice conversion https://github.com/rsxdalv/tts-generation-webui

if you dont like UVR5, try out an alternative 
https://github.com/stemrollerapp/stemroller 
https://github.com/Frikallo/MISST
https://github.com/comfyanonymous/ComfyUI comfy ui extensions

Lots of information is here https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.k3vca4e9ena8

**Comment by RustoMCSpit** [comment]
ModuleNotFoundError: No module named 'imp'

many people have had the above issue

_(It has to do with the fact that the last time UVR was updated, Python 3.11 was the latest version of Python and used this 'imp' module, which was deprecated and replaced with 'importlib' in Python 3.12 (the current version as of 2024))_

you have to use a python environment that is version 3.11.11.
3.12 or above breaks this.
(imp was deprecated in 3.12)

the packages being used here are largely deprecated, this project needs a bit of a clean up no offense!

**Comment by CodesoundR** [comment]
LINUX Mint 22_Cinnamom_x64

Hi,
you probably realized that I needed a guide like that too and you did it! THANK YOU!

```
codesound@worker:~$ python3 --version
Python 3.12.3

codesound@worker:~$ sudo add-apt-repository ppa:deadsnakes/ppa
codesound@worker:~$ sudo apt-get update
codesound@worker:~$ sudo apt-get install python3.11 python3.11-venv python3.11-dev
codesound@worker:~$ python3.11 -m venv ULTIMATEVOCALREMOVERGUI

codesound@worker:~$ source ULTIMATEVOCALREMOVERGUI/bin/activate
(ULTIMATEVOCALREMOVERGUI) codesound@worker:~$ 

```
_on Linux Mint there is NO pip pre-installed, you have to install it before the "pip install" command
 ` sudo apt install pip`

_but once installed, and run the "pip install" command, this is the terminal output:
```
codesound@worker:~$ pip install altgraph==0.17.3 audioread==3.0.0 certifi==2022.12.07 cffi==1.15.1 cryptography==3.4.6 einops==0.6.0 future==0.18.3 julius==0.2.7 kthread==0.2.3 librosa==0.9.2 llvmlite matchering==2.0.6 ml_collections==0.1.1 natsort==8.2.0 omegaconf==2.2.3 opencv-python==4.6.0.66 Pillow==9.3.0 psutil==5.9.4 pydub==0.25.1 pyglet==1.5.23 pyperclip==1.8.2 pyrubberband==0.3.0 pytorch_lightning==2.0.0 PyYAML==6.0 resampy==0.4.2 scipy==1.9.3 soundstretch==1.2 torch urllib3==1.26.12 wget==3.2 samplerate==0.1.0 screeninfo==0.8.1 diffq playsound onnx onnxruntime onnxruntime-gpu onnx2pytorch SoundFile==0.11.0; sys_platform != 'darwin' PySoundFile==0.9.0.post1; sys_platform == 'darwin' numpy==1.23.5
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
sys_platform: command not found
sys_platform: command not found
```

this error appears but I don't understand how to solve it....
come on, maybe we can do it! :-)

**Comment by RustoMCSpit** [comment]
you might want to try re-install and start again, i saw you were having problems earlier and it may be causing issue now. do a fresh install and try again and follow my steps. i saw you were dealing with an externally managed environment issue earlier but you edited, make sure youre inside the venv before downloading the dependencies

**Comment by RustoMCSpit** [comment]
for every file that doesnt work you need to go here and download a zip of the correct version listed in the requirements text (and if a version isnt listed just get the newest one or the one closest to late 2023 as that was when this was last compiled) https://pypi.org/

once you install the compressed file, just do

```
pip install NAMEOFFILE
```

**Comment by RustoMCSpit** [comment]
@Anjok07 please update your readme with my guide

**Comment by Hadeskin666** [comment]
Would somebody be able to help me on the following error I got after following your tutorial ? Everything goes good, except that it is in fact a pain to install stuff on Arch (I use Arch) (btw) and when I do python3 (or any version) UVR.py it doesn't work after a bit of waiting in terminal and displays the error Could not create GL Context (that's from pyglet). To be honest there is a shitload of errors, here is what I get : 
```
(venv) [Hadeskin@arracheur2shell UVR5]$ python3 UVR.py
/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:789: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/UVR.py", line 7257, in <module>
    root = MainWindow()
           ^^^^^^^^^^^^
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/UVR.py", line 1291, in __init__
    self.set_app_font()
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/UVR.py", line 1559, in set_app_font
    pyglet_font.add_file(FONT_MAPPER[MAIN_FONT_NAME])
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/window/__init__.py", line 615, in __init__
    context = config.create_context(gl.current_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/Hadeskin/OneDrive/Bureau/Archives/Apps/UVR5/venv/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

```

I'll be glad to help with any questions you ask my friends

**Comment by Hadeskin666** [comment]
Fuck me, guys you just need to use `export PYGLET_SHADOW_WINDOW=0` and it'll work <3

**Comment by Ne0nLabs** [comment]
thank you so much

**Comment by kacmem** [comment]
`pip install playsound@git+https://github.com/taconi/playsound`
This command can be used temporarily for installing the package tho.

[pip install playsound no longer works #150](https://github.com/TaylorSMarks/playsound/issues/150#issuecomment-1853354583)
