### ISSUE TITLE
Unhandled exception in script upon launching for the first time

### ISSUE THREAD

**Issue by morgancod** [Anjok07/ultimatevocalremovergui#314]
Failed to execute script 'UVR' due to unhandled exception:
[WinError 1445] The paging file is too small for this operation to complete. Error loading "C:\Users\~~~\AppData\Local\Programs\Ultimate Vocal Remover\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

LOG:
Traceback (most recent call last):
  File "UVR.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "inference_MDX.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "torch\__init__.py", line 124, in <module>
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\USER\AppData\Local\Programs\Ultimate Vocal Remover\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

**Comment by TRvlvr** [comment]
Please update UVR to the latest version - https://github.com/Anjok07/ultimatevocalremovergui/releases

**Comment by Anjok07** [comment]
Please try the newest version of UVR here - https://github.com/Anjok07/ultimatevocalremovergui/releases
