### ISSUE TITLE
MacOS (M1, Ventura): did not manage to locate a library called 'sndfile'

### ISSUE THREAD

**Issue by iGerman00** [Anjok07/ultimatevocalremovergui#342]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/soundfile.py", line 267, in <module>
    _snd = _ffi.dlopen('sndfile')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'sndfile'
```

Installed like in the instructions, but, it seems like sndfile is missing. I tried installing it but it doesn't build (https://github.com/sangoma/sndfile/issues/2).

libsndfile is installed with brew

**Comment by iGerman00** [comment]
I did manage to fix it, though, `cp /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_soundfile_data/libsndfile_arm64.dylib /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib`

**Comment by Anjok07** [comment]
Thank you! I added this to the Mac manual installation instructions.
