### ISSUE TITLE
MacOS (M1, Ventura): Try manual download errors out and does nothing

### ISSUE THREAD

**Issue by iGerman00** [Anjok07/ultimatevocalremovergui#343]
Pressing "Try Manual Download" doesn't do anything but print this error into the stdout:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/igmn/uvr/UVR.py", line 2979, in menu_manual_downloads
    manual_downloads_link_Frame = self.menu_FRAME_SET(manual_downloads_menu, thickness=5)
TypeError: MainWindow.menu_FRAME_SET() got an unexpected keyword argument 'thickness'
```

**Comment by iGerman00** [comment]
Replacing the line 2979 in UVR.py with:
```python
        manual_downloads_link_Frame = self.menu_FRAME_SET(manual_downloads_menu)
```
fixes it
