### ISSUE TITLE
The window of the program appears then quits immediately just before an error occured when I tried to deploy the program with docker. In theory, this error will occur on every machine powered by any version of Debian or Ubuntu with GUI support and docker preinstalled by the official command `curl -fsSL https://get.docker.com | bash -s docker`.

### ISSUE THREAD

**Issue by hero-intelligent** [Anjok07/ultimatevocalremovergui#380]
The window of the program appears then quits immediately just before an error occured when I tried to deploy the program with docker. In theory, this error will occur on every machine powered by any version of Debian or Ubuntu with GUI support and docker preinstalled by the official command `curl -fsSL https://get.docker.com | bash -s docker`.
That means, if you have the `x11-xserver-utils` and `docker` preinstalled on Ubuntu or Debian with GUI support, this error can be reproduced.

My commands:
```
git clone https://github.com/Anjok07/ultimatevocalremovergui.git uvr
cd uvr
touch Dockerfile
touch docker-compose.yml
```
then edit the two files and then change to super user mode
```
xhost +
docker compose up
```

Error:

```
Attaching to uvr-uvr-1
uvr-uvr-1  | playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
uvr-uvr-1  | 2023-01-11 18:27:59,177 - UVR BEGIN
uvr-uvr-1  | Traceback (most recent call last):
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/__init__.py", line 336, in __getattr__
uvr-uvr-1  | No splash screen.
uvr-uvr-1  |     return getattr(self._module, name)
uvr-uvr-1  | AttributeError: 'NoneType' object has no attribute 'add_file'
uvr-uvr-1  | 
uvr-uvr-1  | During handling of the above exception, another exception occurred:
uvr-uvr-1  | 
uvr-uvr-1  | Traceback (most recent call last):
uvr-uvr-1  |   File "/uvr/UVR.py", line 5023, in <module>
uvr-uvr-1  |     root = MainWindow()
uvr-uvr-1  |   File "/uvr/UVR.py", line 842, in __init__
uvr-uvr-1  |     font.add_file(FONT_PATH)
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/__init__.py", line 342, in __getattr__
uvr-uvr-1  |     __import__(import_name)
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/font/__init__.py", line 80, in <module>
uvr-uvr-1  |     from pyglet.font.freetype import FreeTypeFont
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/font/freetype.py", line 41, in <module>
uvr-uvr-1  |     from pyglet.font import base
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/font/base.py", line 45, in <module>
uvr-uvr-1  |     from pyglet.gl import *
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/__init__.py", line 95, in <module>
uvr-uvr-1  |     from pyglet.gl.gl import *
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/gl.py", line 45, in <module>
uvr-uvr-1  |     from pyglet.gl.lib import link_GL as _link_function
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/lib.py", line 149, in <module>
uvr-uvr-1  |     from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/gl/lib_glx.py", line 46, in <module>
uvr-uvr-1  |     glu_lib = pyglet.lib.load_library('GLU')
uvr-uvr-1  |   File "/usr/local/lib/python3.10/dist-packages/pyglet/lib.py", line 164, in load_library
uvr-uvr-1  |     raise ImportError('Library "%s" not found.' % names[0])
uvr-uvr-1  | ImportError: Library "GLU" not found.
uvr-uvr-1 exited with code 1
```

This is my `Dockerfile`:

```
FROM ubuntu:22.10

COPY ./requirements.txt /uvr/requirements.txt

WORKDIR /uvr

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata && \
    apt install -y ffmpeg python3-pip python3-tk && \
    pip3 install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple

COPY . /uvr

VOLUME [ "/uvr/sources", "/uvr/results" ]

ENTRYPOINT [ "python3" ]

CMD [ "/uvr/UVR.py" ]
```

And this is my `docker-compose.yml`:

```
version: '3.8'

services:
  uvr:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./sources:/uvr/sources
      - ./results:/uvr/results
    environment:
      - DISPLAY=unix:0.0
      - GDK_SCALE
      - GDK_DPI_SCALE
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: [ '0' ]
#              capabilities: [ gpu ]
```

Besides, my computer has no graphics card.

_Originally posted by @hero-intelligent in https://github.com/Anjok07/ultimatevocalremovergui/issues/379#issuecomment-1378790979_

**Comment by hero-intelligent** [comment]
OK, Problem solved. It's raised by a missing package `freeglut3-dev`.

Now this is my new `Dockerfile`:

```
FROM ubuntu:22.10

COPY ./requirements.txt /uvr/requirements.txt

WORKDIR /uvr

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata && \
    apt install -y ffmpeg python3-pip python3-tk freeglut3-dev x11-xserver-utils && \
    pip3 install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple #This is 中科大 image repository of pip3.
#Change to your own image repository of pip3, or just delete the -i argument if you are not in China.

COPY . /uvr

VOLUME [ "/uvr/sources", "/uvr/results" ]

ENTRYPOINT [ "python3" ]

CMD [ "/uvr/UVR.py" ]
```


The `docker-compose.yml` is the same as before.

But the words are just displayed in half because the window is too small to show words in whole.
At least I can see the program running, but I'm too tired to test if it works well. Let me test it tomorrow.



I strongly recomend that the `Dockerfile` and `docker-compose.yml` should be added to your repository now that it works well and more importantly, this program will not pollute the system anymore.

**Comment by hero-intelligent** [comment]
This issue can be closed, relevant discussions about docker are now in #379 . Thanks for reading.
