### ISSUE TITLE
can not run on Mageia Linux 

### ISSUE THREAD

**Issue by rkarpuzov** [Anjok07/ultimatevocalremovergui#389]
Hello,
I have Mageia Linux x86_64 with RTX 3060 6GM V-RAM. 
First I must install tk via pip3, because there is no generic packages in Mageia's repo.
OK, but when I install the requirements can not run the app:
```
$ python3 UVR.py 
2023-01-21 00:20:05,154 - UVR BEGIN
No splash screen.
Traceback (most recent call last):
  File "UVR.py", line 650, in <module>
    class MainWindow(TkinterDnD.Tk if is_dnd_compatible else tk.Tk):
  File "UVR.py", line 1623, in MainWindow
    def cached_source_model_list_check(self, model_list: list[ModelData]):
TypeError: 'type' object is not subscriptable

```

Looks like there is missing the tkinterdnd package. Installing via pip3 fails:

```
$ pip3 install tkinterDnD
/usr/lib/python3.8/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3.8/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Collecting tkinterDnD
  Downloading tkinterDnD-0.0.0.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement tkinter (from tkinterdnd) (from versions: none)
ERROR: No matching distribution found for tkinter

```
I have already installed tkinter3-3.8.14-1.1.mga8.x86_64

Any suggestions?

Best regards,
Rossen

**Comment by rkarpuzov** [comment]
I found that tkinterDnD2 work fine with python2 and 3, installed, but I see the same error message

**Comment by rkarpuzov** [comment]
I will not migrate to Ubuntu :/

**Comment by rkarpuzov** [comment]
Thank you @Heersin 
This fix works in Mageia
