### ISSUE TITLE
separate.py fails: RequestsDependencyWarning

### ISSUE THREAD

**Issue by atom-smasher** [Anjok07/ultimatevocalremovergui#398]
Ubuntu 20.04.5 LTS
Ultimate Vocal Remover GUI v5.5.0

Running `python3 ./separate.py` fails:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
```

Output from `pip3 show urllib3 chardet`:
```
Name: urllib3
Version: 1.26.12
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: spotipy
---
Name: chardet
Version: 5.1.0
Summary: Universal encoding detector for Python 3
Home-page: https://github.com/chardet/chardet
Author: Mark Pilgrim
Author-email: mark@diveintomark.org
License: LGPL
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: pdfminer.six
```

Any suggestions? Thanks.

**Comment by Anjok07** [comment]
I haven't tested UVR on Ubuntu 20.04. Also, the application runs from the UVR.py file, not the separate.py file.

**Comment by atom-smasher** [comment]
Here's the error I'm getting with `python3 ./UVR.py`:

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2023-01-30 15:52:08,634 - UVR BEGIN
No splash screen.
Traceback (most recent call last):
  File "./UVR.py", line 650, in <module>
    class MainWindow(TkinterDnD.Tk if is_dnd_compatible else tk.Tk):
  File "./UVR.py", line 1623, in MainWindow
    def cached_source_model_list_check(self, model_list: list[ModelData]):
TypeError: 'type' object is not subscriptable
```

**Comment by zhiyixu** [comment]
@atom-smasher same question, have you solve this problem yet?

**Comment by zhiyixu** [comment]
@atom-smasher problem solved! following this [pull records](https://github.com/Anjok07/ultimatevocalremovergui/pull/472/files) and change the content.
good luck!
