### ISSUE TITLE
train model commande line

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#4]
i want train model command line work on cpu , because When I trained my own model, he said that you need an NVIDIA, NVIDIA graphics card I don't own, I have Intel
(base) C:\Users\DESKTOP\Downloads\vocal-remover-v3.0.0\vocal-remover>python train.py -i dataset/instruments -m dataset/mixtures -M 0.5 -g 0
1 05_too_mix.wav 05_too_inst.wav
Traceback (most recent call last):
File "train.py", line 225, in
main()
File "train.py", line 136, in main
model.cuda()
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 458, in cuda
return self._apply(lambda t: t.cuda(device))
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
module._apply(fn)
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
module._apply(fn)
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
module._apply(fn)
[Previous line repeated 2 more times]
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 376, in _apply
param_applied = fn(param)
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 458, in
return self.apply(lambda t: t.cuda(device))
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\cuda_init.py", line 186, in _lazy_init
check_driver()
File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\cuda_init.py", line 68, in _check_driver
http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by AlbyTree** [comment]
You can try to remove the `-g 0` option at the end of your command

`python train.py -i dataset/instruments -m dataset/mixtures -M 0.5`

**Comment by aufr33** [comment]
To train on a cpu, you need an incredibly powerful processor like 3990X. If your inference execution speed is [100-200s/it](https://github.com/tsurumeso/vocal-remover/issues/42), then training will take about 20 years!

**Comment by 404000** [comment]
AlbyTree I tried this command line, but it gave me this message about nvidea driver
(base) C:\Users\DESKTOP\Downloads\vocal-remover-v3.0.0\vocal-remover>python train.py -i dataset/instruments -m dataset/mixtures -M 0.5
1 08_uar_mix.mp3 08_uar_inst.mp3
2 05_too_mix.wav 05_too_inst.wav
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:48<00:00, 24.22s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 19/19 [08:07<00:00, 25.66s/it]
# epoch 0
  * inner epoch 0
Traceback (most recent call last):
  File "train.py", line 225, in <module>
    main()
  File "train.py", line 201, in main
    reduction_mask=reduction_mask)
  File "train.py", line 38, in train_inner_epoch
    X_mag = torch.from_numpy(X_mag).cuda()
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init
    _check_driver()
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 68, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by AlbyTree** [comment]
It looks like that even if you specify that you **want to use the CPU** for training, the code actually uses some functionality(i.e. CUDA) **only available on NVIDIA GPU**: you should open a **new issue** on [the original creator page](https://github.com/tsurumeso/vocal-remover/issues) and **ask if you can train a model with only CPU**.
