### ISSUE TITLE
masOS, app crashes on launch

### ISSUE THREAD

**Issue by NathanR-85** [Anjok07/ultimatevocalremovergui#401]
Using the **non-M1** version on macOS (Monterey 12.6.1) the app crashes after the icon bounces 1-2 times. On first run it completed the verification process which takes about a minute, but now it just crashes before showing the GUI.

I tried the terminal commands but they didn't seem to change anything in my case (and yes I installed the app to the normal Applications folder).

**Comment by Anjok07** [comment]
Thank you for reporting this. It's possible this is due to MacOS security preventing the application from opening. 

Please try the following:

1. From the Applications folder right-click Ultimate Vocal Remover and select "Show Package Contents".
2. Open the following Contents->MacOS->UVR
3. A terminal console should pop-up and provide an error message. 
4. Paste the error message here or try the following:
    - [Click here](https://github.com/Anjok07/ultimatevocalremovergui#macos-installation) and follow the instruction under "MacOS Users: Having Trouble Opening UVR?" (be sure to click the arrow to expand the section).

**Comment by okt04175** [comment]
> Thank you for reporting this. It's possible this is due to MacOS security preventing the application from opening.
> 
> Please try the following:
> 
> 1. From the Applications folder right-click Ultimate Vocal Remover and select "Show Package Contents".
> 2. Open the following Contents->MacOS->UVR
> 3. A terminal console should pop-up and provide an error message.
> 4. Paste the error message here or try the following:
>    
>    * [Click here](https://github.com/Anjok07/ultimatevocalremovergui#macos-installation) and follow the instruction under "MacOS Users: Having Trouble Opening UVR?" (be sure to click the arrow to expand the section).

terminal console error message:
zsh: segmentation fault  /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR

**Comment by NathanR-85** [comment]
```
Last login: Mon Jan 30 11:09:07 on ttys000
/Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;           
~ % /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
Traceback (most recent call last):
  File "UVR.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/util/utils.py", line 1879, in <module>
  File "numba/core/decorators.py", line 212, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[50267] Failed to execute script 'UVR' due to unhandled exception: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[50267] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "librosa/util/utils.py", line 1879, in <module>
  File "numba/core/decorators.py", line 212, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'


Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]




```

**Comment by vyconm** [comment]
I can reproduce the exact same error message, same crashing behaviour.

arm64 M1Max 64GB Macbook Pro running Sonoma 14.3, have had this issue since Sonoma beta 14.0.

Lates UVR 5.6 arm4 package, same problem with same error message using the Intel64 binary running rosetta.

**Comment by baka-gourd** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/issues/1260#issuecomment-2122093427
