### ISSUE TITLE
No longer working out of nowhere

### ISSUE THREAD

**Issue by Googzie** [Anjok07/ultimatevocalremovergui#473]
I use it almost every day without messing on anything i don't know, so i only go between the separated and tracks folders, but suddenly it stopped working with any model i used, and it's giving the message:

loading model... done
stft of wave source... Traceback (most recent call last):
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 307, in <module>
    main()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 293, in main
    multi_file(useModel, args.input)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 244, in multi_file
    process.inference()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 94, in inference
    X_spec_m, input_high_end_h, input_high_end = spec_utils.loadWave(self.input, mp, hep=self.hep)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 14, in loadWave
    X_wave[bands_n+1], _ = librosa.load(
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given

How do I fix it?

**Comment by Anjok07** [comment]
I do not provide support for the Colab version since I did not write it.

**Comment by upright2003** [comment]
There is a problem with the librosa library version, just reinstall the old one, and run the following two lines to test it out
!pip uninstall librosa -y
!pip install librosa==0.8.1
