### ISSUE TITLE
Error in UVR "Unhandled exception in script Failed to execute script 'UVR' due to unhandled exception: Can't find a usable init.tcl in the following directories"

### ISSUE THREAD

**Issue by GooogGd** [Anjok07/ultimatevocalremovergui#535]
Unhandled exception in script
Failed to execute script 'UVR' due to unhandled exception: Can't find a usable init.tcl in the following directories:
Vocal Remover\tcl} {C:/Users/àðóóc/AppData/Local/Programs/Íîâàÿïàïêà/Ultimate
{C:\Users\àðóóç\AppData\Local\Programs\Íîâàÿïàïêà\Ultimate Vocal Remover/tcl8.6} {C:/Users/apбy3/AppData/Local/Programs/HoBaя nanka/lib/tcl8.6} {C:/Users/apбy3/AppData/Local/Programs/HoBaя C:/Users/apбy3/AppData/Local/tcl8.6.9/library
nanka/lib/tcl8.6} C:/Users/apбy3/AppData/Local/Programs/lib/tcl8.6
{C:/Users/apбy3/AppData/Local/Programs/Hoвaя пanka/library}
C:/Users/ap6y3/AppData/Local/Programs/library C:/Users/apбy3/AppData/Local/Programs/tcl8.6.9/library
This probably means that Tcl wasn't installed properly.
Traceback (most recent call last):
File "UVR.py", line 5023, in <module>
File "UVR.py", line 666, in __init__ File "gui_data\tkinterdnd2\TkinterDnD.py", line 285, in __init__
tkinter.Tk.__init__(self, *args, **kw) File "tkinter\__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directori {C:\Users\àõáóç\AppData\Local\Programs\Íîâàÿïàïêà\Ultimate Vocal Remover\tcl} {C:/Users/àðáóç/AppData/Local/Programs/Íîâàÿ ïàïêà/Ultimate Vocal Remover/tcl8.6} {C:/Users/арбуз/AppData/Local/Programs/Новая папка/lib/tcl8.6} {C:/Users/арбуз/AppData/Local/Programs/Новая папка/lib/tcl8.6} C:/Users/арбуз/AppData/Local/Programs/lib/tcl8.6 {C:/Users/арбуз/AppData/Local/Programs/Новая папка/library} C:/Users/арбуз/AppData/Local/Programs/library C:/Users/арбуз/AppData/Local/Programs/tcl8.6.9/library C:/Users/арбуз/AppData/Local/tcl8.6.9/library
![image](https://user-images.githubusercontent.com/132740613/236609755-09cf49f2-ea18-41f0-84c7-f721e49ad46d.png)

**Comment by Tommyfat** [comment]
Fiexd? 
Same problem.

**Comment by pocancik** [comment]
it is necessary to remove the Cyrillic alphabet from the destination path

**Comment by Adam4Test** [comment]
Just install it in an English folder

**Comment by Ruslan01021985** [comment]
> Просто установите его в английскую папку

объясните пожалуйста для чайников, что нужно сделать ? более конкретно

**Comment by guzhovmusic** [comment]
C:/Users/ap6y3/ проблема в том что папка (пользователь) имеет название состоящее из букв Кириллицы (русских) нужно создать пользователя с названием на английском языке и установить туда
