### ISSUE TITLE
vocalremover.py doesn't open

### ISSUE THREAD

**Issue by jordanttt** [Anjok07/ultimatevocalremovergui#54]
Hi everyone. I can't seem to run vocalremover.py. It just doesn't open. This is what I got:

Traceback (most recent call last):
  File "VocalRemover.py", line 25, in <module>
    import inference_v2
  File "C:\Users\thijs\UVR-V4GUI\inference_v2.py", line 5, in <module>
    import librosa
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\thijs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Kan opgegeven module niet vinden

Thank you in advance!

**Comment by jordanttt** [comment]
No one?

**Comment by DilanBoskan** [comment]
Please make sure your library installation versions match the ones in the requirements.txt file
