### ISSUE TITLE
Error installing requirements

### ISSUE THREAD

**Issue by malaksyan64** [Anjok07/ultimatevocalremovergui#557]
[spiros@ryzen ultimatevocalremovergui-master]$ pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Ignoring SoundFile: markers 'sys_platform == "windows"' don't match your environment
Collecting altgraph==0.17.3 (from -r requirements.txt (line 1))
  Using cached altgraph-0.17.3-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: audioread==3.0.0 in /home/spiros/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: certifi==2022.12.7 in /usr/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: cffi==1.15.1 in /usr/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (1.15.1)
Collecting cryptography==3.4.6 (from -r requirements.txt (line 5))
  Using cached cryptography-3.4.6-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
Collecting diffq==0.2.3 (from -r requirements.txt (line 6))
  Using cached diffq-0.2.3.tar.gz (46 kB)
  Preparing metadata (setup.py) ... done
Collecting Dora==0.0.3 (from -r requirements.txt (line 7))
  Using cached Dora-0.0.3.tar.gz (4.9 kB)
  Preparing metadata (setup.py) ... done
Collecting einops==0.6.0 (from -r requirements.txt (line 8))
  Using cached einops-0.6.0-py3-none-any.whl (41 kB)
Requirement already satisfied: future==0.18.2 in /usr/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (0.18.2)
Requirement already satisfied: julius==0.2.7 in /home/spiros/.local/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (0.2.7)
Requirement already satisfied: kthread==0.2.3 in /home/spiros/.local/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (0.2.3)
Collecting librosa==0.9.2 (from -r requirements.txt (line 12))
  Using cached librosa-0.9.2-py3-none-any.whl (214 kB)
Collecting llvmlite==0.39.1 (from -r requirements.txt (line 13))
  Using cached llvmlite-0.39.1.tar.gz (132 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-udpbc78y/llvmlite_923196e3d7b34d1baab53ed931333e53/setup.py", line 55, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-udpbc78y/llvmlite_923196e3d7b34d1baab53ed931333e53/setup.py", line 52, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sleeplessKomodo** [comment]
Same problem. Is there a way to install using a virtual environment to satisfy the python version <3.11 issue?

**Comment by EmersonBiggons** [comment]
> Same problem (on Fedora Linux). Is there a way to install using a virtual environment to satisfy the python version <3.11 issue?

Just run `python3.11 -m venv venv` and you should be fine assuming nothing else goes wrong
