### ISSUE TITLE
can't run GUI in virtual environment on arch linux

### ISSUE THREAD

**Issue by albert-softie** [Anjok07/ultimatevocalremovergui#603]
been trying to set up UVR GUI in a virtual environment using the following steps:
`$ python3.9 -m venv venv`
`$ source venv/bin/activate`
`$ pip3 install -r requirements.txt`
but when actually trying to run UVR.py inside the venv using python3 i get the following error:
```
Traceback (most recent call last):
  File "/home/albert-softie/source/ultimatevocalremovergui-master/UVR.py", line 26, in <module>
    import tkinter as tk
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'```

**Comment by 641i130** [comment]
Use `yay -S python-conda`
Follow:
https://wiki.archlinux.org/title/Conda
Make sure to update the conda init with this path: `/opt/anaconda/etc/profile.d/conda.sh`
If you're using ZSH like me, do this:
```bash
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/usr/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```
(Append to `.zshrc`)

I'm working on figuring out why it won't launch, I'm at this step:
```bash
# python3 UVR.py
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
2023-06-12 23:31:52,089 - UVR BEGIN
No splash screen.
Traceback (most recent call last):
  File "UVR.py", line 695, in <module>
    class MainWindow(TkinterDnD.Tk if is_dnd_compatible else tk.Tk):
  File "UVR.py", line 1689, in MainWindow
    def cached_source_model_list_check(self, model_list: list[ModelData]):
TypeError: 'type' object is not subscriptable
(uvr) 
```

**Comment by 641i130** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/pull/472
Follow this to get it working. I'm able to run it now :D

**Comment by albert-softie** [comment]
that did the trick, thank you.

**Comment by GUUser91** [comment]
My artix linux build has a tk / tkinter package that only works on python3.12. I was able to to successfully run the app file on a python3.12 virutal environment. This is how I did it. I edit the requirements.txt file and remove the specific version lines for audioread, pyrubberband, PyYAML, scipy, numpy. I deleted the soundfile line from the requirements.txt file. I do these commands.
```
pip install setuptools wheel
```
```
pip install --upgrade setuptools wheel
```
```
pip install playsound pyrubberband soundfile
```

```
pip install -r requirements.txt
```
