### ISSUE TITLE
ImportError: cannot import name 'bitpack' from partially initialized module 'diffq' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by marufmoinuddin** [Anjok07/ultimatevocalremovergui#687]
While installing older version 5.4.0 of uvr in my Linux machine it throws me this error. I am using conda python 3.8 environment with the requirements installed.

```
Traceback (most recent call last):
  File "UVR.py", line 46, in <module>
    import inference_MDX
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/inference_MDX.py", line 2, in <module>
    from demucs.apply import BagOfModels, apply_model
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/demucs/apply.py", line 19, in <module>
    from .demucs import Demucs
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/demucs/demucs.py", line 15, in <module>
    from .states import capture_init
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/demucs/states.py", line 19, in <module>
    from diffq import DiffQuantizer, UniformQuantizer, restore_quantized_state
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/diffq/__init__.py", line 22, in <module>
    from .uniform import UniformQuantizer
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/diffq/uniform.py", line 13, in <module>
    from .base import BaseQuantizer
  File "/mnt/Media/AI/ultimatevocalremovergui-5.4.0/diffq/base.py", line 21, in <module>
    from . import bitpack
ImportError: cannot import name 'bitpack' from partially initialized module 'diffq' (most likely due to a circular import) (/mnt/Media/AI/ultimatevocalremovergui-5.4.0/diffq/__init__.py)
```

**Comment by marufmoinuddin** [comment]
nvm it is os specific problem i understood. i need to replace diffq directory for linux. (more in this closed issue [232](https://github.com/Anjok07/ultimatevocalremovergui/issues/232#issue-1316727136))
