### ISSUE TITLE
Not opening on macOS Monterey M1

### ISSUE THREAD

**Issue by GageHoweTamu** [Anjok07/ultimatevocalremovergui#713]
Tried using the installer and instructions given for if the app doesn't open, and it still doesn't work. The app icon bounces once and doesn't open.

**Comment by GageHoweTamu** [comment]
Update: got this when the UVR executable was run: Last login: Tue Aug  1 23:03:39 on ttys004
/Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
(base) gagehowe@GagesMusicEngineeringLaptop ~ % /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
Traceback (most recent call last):
  File "UVR.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/util/utils.py", line 1879, in <module>
  File "numba/core/decorators.py", line 212, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[10699] Failed to execute script 'UVR' due to unhandled exception: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'
[10699] Traceback:
Traceback (most recent call last):
  File "UVR.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/core/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/core/convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/core/notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/util/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "librosa/util/utils.py", line 1879, in <module>
  File "numba/core/decorators.py", line 212, in wrapper
  File "numba/core/dispatcher.py", line 863, in enable_caching
  File "numba/core/caching.py", line 601, in __init__
  File "numba/core/caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa/util/utils.py'


Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
