### ISSUE TITLE
Tcl wasn't installed properly

### ISSUE THREAD

**Issue by unluckykebab** [Anjok07/ultimatevocalremovergui#723]
Hi I've just downloaded and installed UVR but when I wanted to open I faced this problem

Traceback (most recent call last):
  File "UVR.py", line 5160, in <module>
  File "UVR.py", line 711, in __init__
  File "gui_data\tkinterdnd2\TkinterDnD.py", line 285, in __init__
    tkinter.Tk.__init__(self, *args, **kw)
  File "tkinter\__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {C:\Users\Berat Hikmet Canoðlu\AppData\Local\Programs\Ultimate Vocal Remover\tcl} {C:/Users/Berat Hikmet Canoðlu/AppData/Local/Programs/Ultimate Vocal Remover/tcl8.6} {C:/Users/Berat Hikmet Canoğlu/AppData/Local/Programs/lib/tcl8.6} {C:/Users/Berat Hikmet Canoğlu/AppData/Local/Programs/lib/tcl8.6} {C:/Users/Berat Hikmet Canoğlu/AppData/Local/lib/tcl8.6} {C:/Users/Berat Hikmet Canoğlu/AppData/Local/Programs/library} {C:/Users/Berat Hikmet Canoğlu/AppData/Local/library} {C:/Users/Berat Hikmet Canoğlu/AppData/Local/tcl8.6.9/library} {C:/Users/Berat Hikmet Canoğlu/AppData/tcl8.6.9/library}

This probably means that Tcl wasn't installed properly.

I re-installed the program but it didn't work please help

**Comment by unluckykebab** [comment]
Okay I made it. It was because of the Turkish character in the name of the folder.

**Comment by mcraenemo** [comment]
How did you solve this problem? I also encountered the same problem
