### ISSUE TITLE
Cannot open after install

### ISSUE THREAD

**Issue by BKGlo** [Anjok07/ultimatevocalremovergui#744]
![image](https://github.com/Anjok07/ultimatevocalremovergui/assets/105865069/e601353e-36ed-4cdb-9282-8b13f1c9fb48)

Traceback (most recent call last):
  File "UVR.py", line 5160, in <module>
  File "UVR.py", line 711, in __init__
  File "gui_data\tkinterdnd2\TkinterDnD.py", line 285, in __init__
    tkinter.Tk.__init__(self, *args, **kw)
  File "tkinter\__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {E:\Èí¼þ\Ultimate Vocal Remover\tcl} {E:/Èí¼þ/Ultimate Vocal Remover/tcl8.6} E:/软件/lib/tcl8.6 E:/软件/lib/tcl8.6 E:/lib/tcl8.6 E:/软件/library E:/library E:/tcl8.6.9/library E:/tcl8.6.9/library

This probably means that Tcl wasn't installed properly.

**Comment by PRKn91** [comment]
i have the same 👍 Traceback (most recent call last):
  File "UVR.py", line 5160, in <module>
  File "UVR.py", line 711, in __init__
  File "gui_data\tkinterdnd2\TkinterDnD.py", line 285, in __init__
    tkinter.Tk.__init__(self, *args, **kw)
  File "tkinter\__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {C:\Users\JÃ¶rg Seeliger\AppData\Local\Programs\Ultimate Vocal Remover\tcl} {C:/Users/JÃ¶rg Seeliger/AppData/Local/Programs/Ultimate Vocal Remover/tcl8.6} {C:/Users/Jörg Seeliger/AppData/Local/Programs/lib/tcl8.6} {C:/Users/Jörg Seeliger/AppData/Local/Programs/lib/tcl8.6} {C:/Users/Jörg Seeliger/AppData/Local/lib/tcl8.6} {C:/Users/Jörg Seeliger/AppData/Local/Programs/library} {C:/Users/Jörg Seeliger/AppData/Local/library} {C:/Users/Jörg Seeliger/AppData/Local/tcl8.6.9/library} {C:/Users/Jörg Seeliger/AppData/tcl8.6.9/library}



This probably means that Tcl wasn't installed properly.

**Comment by PRKn91** [comment]
![grafik](https://github.com/Anjok07/ultimatevocalremovergui/assets/142677362/0cd5990d-dbf9-42cd-bf00-94ff7e194fe2)

**Comment by aerin2** [comment]
I have the same problem, please tell me how to solve it
![Ekran görüntüsü 2023-08-30 193652](https://github.com/Anjok07/ultimatevocalremovergui/assets/143639309/b4a351cd-eb21-40cd-94b1-a5aad6eb2af2)
****
