### ISSUE TITLE
GL context error on Linux

### ISSUE THREAD

**Issue by oatsvine** [Anjok07/ultimatevocalremovergui#756]
I build from the instructions and get this error:

```
❯ python ./UVR.py
2023-08-21 21:51:24,947 - UVR BEGIN
No splash screen.
libGL error: MESA-LOADER: failed to open iris: /home/user/.conda/envs/torch/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /home/user/.conda/envs/torch/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /home/user/.conda/envs/torch/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/src/ultimatevocalremovergui/./UVR.py", line 5160, in <module>
    root = MainWindow()
  File "/home/user/src/ultimatevocalremovergui/./UVR.py", line 889, in __init__
    font.add_file(FONT_PATH)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/window/__init__.py", line 615, in __init__
    context = config.create_context(gl.current_context)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/user/.conda/envs/torch/lib/python3.9/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
(torch)
```
I can't see to build at all with python 3.10. This is from master at the time of writing.

**Comment by iamargelh** [comment]
use `export PYGLET_SHADOW_WINDOW=0`
an then `python UVR.py`

**Comment by RandomErrorkun** [comment]
> use `export PYGLET_SHADOW_WINDOW=0` and then `python UVR.py`

This worked for me, thanks~
