### ISSUE TITLE
v5bug

### ISSUE THREAD

**Issue by splinter21** [Anjok07/ultimatevocalremovergui#76]
Environments:
Win10
Pytorch==1.8.1+cu111
Other models are ok.
But when running "python inference.py -g 0 -m modelparams\2band_32000.json -P models\MGM-v5-KAROKEE-32000-BETA2-AGR.pth  -i xxx.wav"......

Here are the errors:
loading model... Traceback (most recent call last):
  File "inference.py", line 282, in <module>
    main()
  File "inference.py", line 132, in main
    model.load_state_dict(torch.load(args.pretrained_model, map_location=device))
  File "C:\Users\liujing\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 586, in load
    if _is_torchscript_zip(opened_zipfile):
  File "C:\Users\liujing\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\serialization.py", line 859, in _is_torchscript_zip
    return 'constants.pkl' in zip_file.get_all_records()
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:211] . file in archive is not in a subdirectory archive/: param.json

**Comment by splinter21** [comment]
python3.6.4

**Comment by aufr33** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/issues/63#issuecomment-829858503
