### ISSUE TITLE
Pyparsing error

### ISSUE THREAD

**Issue by Diego92Ita** [Anjok07/ultimatevocalremovergui#79]
I get this error messagge whenever I type "python VocalRemover.py". I've installed all requirements

Traceback (most recent call last):
  File "VocalRemover.py", line 25, in <module>
    import inference_v2
  File "/Users/diegocraducci/Desktop/Ultimate Vocal Remover v4/inference_v2.py", line 5, in <module>
    import librosa
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/numba/__init__.py", line 30, in <module>
    from .decorators import (cfunc, generated_jit, jit, njit, stencil, jit_module)
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/numba/decorators.py", line 14, in <module>
    from .targets import registry
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/numba/targets/registry.py", line 5, in <module>
    from . import cpu
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/numba/targets/cpu.py", line 20, in <module>
    import numba.entrypoints
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/numba/entrypoints.py", line 3, in <module>
    from pkg_resources import iter_entry_points
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "/Users/diegocraducci/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 54, in load_module
    "distribution.".format(**locals())
ImportError: The 'pyparsing' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

**Comment by DilanBoskan** [comment]
Please try:

`pip uninstall tensorflow`

then

`pip install tensorflow`

and

`pip install pyparsing`

**Comment by Diego92Ita** [comment]
Resolved
