### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by GuglPlay** [Anjok07/ultimatevocalremovergui#84]
I have issue when instal by _pip install --no-cache-dir -r requirements.txt_

```
Installing collected packages: llvmlite, threadpoolctl, scipy, numba, joblib, SoundFile, scikit-learn, resampy, decorator, audioread, tqdm, soundstretch, Pillow, opencv-python, librosa
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\OLEG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\OLEG\\AppData\\Local\\Temp\\pip-install-cqwzw0nj\\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\\setup.py'"'"'; __file__='"'"'C:\\Users\\OLEG\\AppData\\Local\\Temp\\pip-install-cqwzw0nj\\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\OLEG\AppData\Local\Temp\pip-record-wtpjl12e\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\OLEG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\llvmlite'
         cwd: C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\
    Complete output (27 lines):
    running install
    running build
    got version from file C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    C:\Users\OLEG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\ffi\build.py
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\ffi\build.py", line 168, in <module>
        main()
      File "C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\ffi\build.py", line 156, in main
        main_win32()
      File "C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\OLEG\AppData\Local\Temp\pip-install-cqwzw0nj\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 368, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 349, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] Не удается найти указанный файл
    error: command 'C:\\Users\\OLEG\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\OLEG\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\OLEG\\AppData\\Local\\Temp\\pip-install-cqwzw0nj\\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\\setup.py'"'"'; __file__='"'"'C:\\Users\\OLEG\\AppData\\Local\\Temp\\pip-install-cqwzw0nj\\llvmlite_956c16c0f486432b99d9c4d67c9f1c06\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\OLEG\AppData\Local\Temp\pip-record-wtpjl12e\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\OLEG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\llvmlite' Check the logs for full command output.
```

**Comment by KimberleyJensen** [comment]
Use python 3.7 not 3.9
