### ISSUE TITLE
Installation error in Linux Mint 21.1

### ISSUE THREAD

**Issue by SmoothBrainApe** [Anjok07/ultimatevocalremovergui#855]
~/ultimatevocalremovergui-master$ python3 UVR.py 
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
Traceback (most recent call last):
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 7176, in <module>
    root = MainWindow()
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 1275, in __init__
    self.set_app_font()
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 1541, in set_app_font
    pyglet_font.add_file(FONT_MAPPER[MAIN_FONT_NAME])
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/window/__init__.py", line 658, in __init__
    self._create()
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 393, in _create
    self.set_caption(self._caption)
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 552, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/home/chupz22/venv/uvrvenv/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 869, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property

Got this error after installing requirements. I used venv to isolate environment.

**Comment by SmoothBrainApe** [comment]
I reinstalled venv and everything. Now i got this error.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.2 requires protobuf<4,>=3.11, but you have protobuf 4.24.4 which is incompatible.
xformers 0.0.20 requires torch==2.0.1, but you have torch 2.1.0 which is incompatible.

which versions should be used for which? I tried downgrading protobuf but got alot more errors that needs this version of protobuf

**Comment by SmoothBrainApe** [comment]
I reinstalled torch to 2.0.1 and got this error when running UVR.py

~/ultimatevocalremovergui-master$ python3 UVR.py 
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.22.1ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.22.1ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 7176, in <module>
    root = MainWindow()
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 1275, in __init__
    self.set_app_font()
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 1541, in set_app_font
    pyglet_font.add_file(FONT_MAPPER[MAIN_FONT_NAME])
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/__init__.py", line 658, in __init__
    self._create()
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 393, in _create
    self.set_caption(self._caption)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 552, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 869, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property

not sure what to do anymore

**Comment by SmoothBrainApe** [comment]
Could this be Mint is not supported becaus it is ubuntu based?

**Comment by RustoMCSpit** [comment]
> Could this be Mint is not supported becaus it is ubuntu based?

ubuntu based is officially supported

**Comment by RustoMCSpit** [comment]
uhhh try this pip install pygobject

**Comment by RustoMCSpit** [comment]
> Could this be Mint is not supported becaus it is ubuntu based?

2.22.1ubuntu1 is an invalid version and will not be supported in a future release

what version of mint are you using???

**Comment by RustoMCSpit** [comment]
>  I used venv to isolate environment.

right, could you try run the program without venv and see what happens on a clean install of uvrg

**Comment by SmoothBrainApe** [comment]
> uhhh try this pip install pygobject

~/ultimatevocalremovergui-master$ pip install pygobject
Collecting pygobject
  Using cached PyGObject-3.46.0.tar.gz (723 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Collecting setuptools
        Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Collecting wheel
        Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Collecting pycairo
        Using cached pycairo-1.25.0.tar.gz (347 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-310
            creating build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

LM 21.1 runs on 22.04 ubuntu

I will try without venv and will let you know

**Comment by SmoothBrainApe** [comment]
This is the error without venv

/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.22.1ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.22.1ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 7176, in <module>
    root = MainWindow()
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 1275, in __init__
    self.set_app_font()
  File "/home/chupz22/ultimatevocalremovergui-master/UVR.py", line 1541, in set_app_font
    pyglet_font.add_file(FONT_MAPPER[MAIN_FONT_NAME])
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 232, in <module>
    import pyglet.window
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/__init__.py", line 658, in __init__
    self._create()
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 393, in _create
    self.set_caption(self._caption)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 552, in set_caption
    self._set_text_property('_NET_WM_NAME', caption)
  File "/home/chupz22/.local/lib/python3.10/site-packages/pyglet/window/xlib/__init__.py", line 869, in _set_text_property
    raise XlibException('Could not create UTF8 text property')
pyglet.window.xlib.XlibException: Could not create UTF8 text property

**Comment by SmoothBrainApe** [comment]
I guess the ubuntu version of linux mint is not supported.

**Comment by Pedulla** [comment]
[https://github.com/Anjok07/ultimatevocalremovergui/pull/1068#issuecomment-2298138380](url)

This works on Mint22
