### ISSUE TITLE
VocalRemover.py fails to run

### ISSUE THREAD

**Issue by atom-smasher** [Anjok07/ultimatevocalremovergui#89]
**Describe the bug**

./VocalRemover.py fails to open.

**To Reproduce**

Installed in /tmp/ultimatevocalremovergui-master/

Run: `python3 ./VocalRemover.py`

Output in console: 
`/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "./VocalRemover.py", line 985, in <module>
    root = MainWindow()
  File "./VocalRemover.py", line 271, in __init__
    self.iconbitmap(icon_path)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/tmp/ultimatevocalremovergui-master/img/UVR-icon.ico" not defined
`

Exit code: 1

**Expected behavior**

I was expecting a GUI to open up.

**Screenshots**

N/A

**Desktop (please complete the following information):**

Ubuntu 20.04.2 LTS

**Additional context**

N/A

**Comment by atom-smasher** [comment]
Here's a patch file that gets past that error, by just omitting the icon -

```--- VocalRemover.py	2021-06-15 13:27:58.000000000 +1200
+++ /tmp/VocalRemover.py	2021-07-22 15:51:36.802469153 +1200
@@ -41,7 +41,7 @@
 stackedModels_dir = os.path.join(base_path, 'models')
 banner_path = os.path.join(base_path, image_foler, 'UVR-banner.png')
 refresh_path = os.path.join(base_path, image_foler, 'refresh.png')
-icon_path = os.path.join(base_path, image_foler, 'UVR-icon.ico')
+#icon_path = os.path.join(base_path, image_foler, 'UVR-icon.ico')
 DEFAULT_DATA = {
     'exportPath': '',
     'inputPaths': [],
@@ -268,7 +268,7 @@
             ypad=int(self.winfo_screenheight()/2 - height/2 - 30)))
         self.configure(bg='#000000')  # Set background color to black
         self.protocol("WM_DELETE_WINDOW", self.save_values)
-        self.iconbitmap(icon_path)
+        #self.iconbitmap(icon_path)
         self.resizable(False, False)
         self.update()```


The good news: That  opens a GUI interface without error.

The bad news: The "Choose Main Model" drop-down is empty, resulting an the GUI producing an error: **You have selected an invalid main model file! Please make sure that your model file still exists!**

**Comment by DilanBoskan** [comment]
You will need to add models to use the application

atom-smasher ***@***.***> schrieb am Do., 22. Juli 2021,
06:03:

**Comment by atom-smasher** [comment]
> You will need to add models to use the application

Yeah. Not clear in the documentation, but I downloaded "models.zip" from here - https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v4.0.1 - unzipped into the "models" directory, and it's working well, now.

Of course, I still need to comment-out the lines about the icon, to get the GUI to run.
