### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by Protegent** [Anjok07/ultimatevocalremovergui#96]
Whenever I run the second command, it gets stuck at 79% and eventually gives an error. the error is as follows:
`Exception:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 302, in _error_catcher
    yield
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 384, in read
    data = self._fp.read(amt)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "c:\users\user\appdata\local\programs\python\python37\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "c:\users\user\appdata\local\programs\python\python37\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "c:\users\user\appdata\local\programs\python\python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\user\appdata\local\programs\python\python37\lib\ssl.py", line 1049, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\user\appdata\local\programs\python\python37\lib\ssl.py", line 908, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\download.py", line 674, in unpack_http_url
    progress_bar)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\download.py", line 620, in _download_url
    consume(downloaded_chunks)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\misc.py", line 843, in consume
    deque(iterator, maxlen=0)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\download.py", line 586, in written_chunks
    for chunk in chunks:
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\ui.py", line 159, in iter
    for x in it:
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\download.py", line 575, in resp_read
    decode_content=False):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\user\appdata\local\programs\python\python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\urllib3\response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.`
(oops, I meant for it to be formatted as code)

**Comment by KimberleyJensen** [comment]
Try this 

pip install --default-timeout=1000 torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Protegent** [comment]
I did that, but now it gives the error at 55%.

**Comment by KimberleyJensen** [comment]
Go to Control panel then Network and sharing Center then Change adapter settings then right click on your current connection and choose properties and uncheck the box with TCP/IPv6

![Capture](https://user-images.githubusercontent.com/84926118/128599454-75369f72-eb63-4778-84b2-f34667aae7b1.PNG)



Then try again
