### ISSUE TITLE
ModuleNotFoundError: No module named '_soundfile'

### ISSUE THREAD

**Issue by MoolsDogTwo** [Anjok07/ultimatevocalremovergui#963]
I'm using Arch Linux and I installed all packages using the install_packages.sh script. But whenever I run `python UVR.py` it spits out this error

Traceback (most recent call last):
  File "/home/aleksandar/Documents/ultimatevocalremovergui-master/UVR.py", line 8, in <module>
    import librosa
  File "/home/aleksandar/.local/lib/python3.11/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/home/aleksandar/.local/lib/python3.11/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/aleksandar/.local/lib/python3.11/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/home/aleksandar/.local/lib/python3.11/site-packages/soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
ModuleNotFoundError: No module named '_soundfile'

Pip already says I have soundfile installed so what is going on here?

**Comment by MoolsDogTwo** [comment]
Nvm I just reinstalled soundfile and now it works. I am a bit dummy.
