### ISSUE TITLE
application wont start

### ISSUE THREAD

**Issue by KillingWithlove** [Anjok07/ultimatevocalremovergui#98]
**Describe the bug**
application wont load/crashes

 - OS: windows 10

PS C:\Users\XXXX\Desktop\UVR-V4GUI> python VocalRemover.py
Traceback (most recent call last):
  File "VocalRemover.py", line 982, in <module>
    root = MainWindow()
  File "VocalRemover.py", line 282, in __init__
    data = load_data()
  File "VocalRemover.py", line 120, in load_data
    data = pickle.load(data_file)
_pickle.UnpicklingError: invalid load key, '\x00'.

I tried reinstalling all didnt help.

**Comment by KillingWithlove** [comment]
re-downloading the Vocalremver and deleting the old one worked.
