### ISSUE TITLE
Error using python3 UVR.py

### ISSUE THREAD

**Issue by nananknow** [Anjok07/ultimatevocalremovergui#990]
Someone help me please im going crazy i dont know what im doing its been hours someone has to save my sanity. Ive been trying to install UVR v5 on my chromebook using Linux ubuntu for like hours bur as soon as i run python3 UVR.py to launch it (i think?) i get this:

```
python3 UVR.py
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
Traceback (most recent call last):
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/__init__.py", line 336, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'add_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/domnickilana14/ultimatevocalremovergui-master/ultimatevocalremovergui-master/UVR.py", line 7257, in <module>
    root = MainWindow()
  File "/home/domnickilana14/ultimatevocalremovergui-master/ultimatevocalremovergui-master/UVR.py", line 1291, in __init__
    self.set_app_font()
  File "/home/domnickilana14/ultimatevocalremovergui-master/ultimatevocalremovergui-master/UVR.py", line 1559, in set_app_font
    pyglet_font.add_file(FONT_MAPPER[MAIN_FONT_NAME])
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/__init__.py", line 342, in __getattr__
    __import__(import_name)
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/font/__init__.py", line 80, in <module>
    from pyglet.font.freetype import FreeTypeFont
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/font/freetype.py", line 41, in <module>
    from pyglet.font import base
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/font/base.py", line 45, in <module>
    from pyglet.gl import *
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/domnickilana14/.local/lib/python3.9/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.
```

and ive been scrolling through issues for so long and googling and trying different stuff im about to give up but itd be a waste after using so much time on it SOMEONE PLS HELP ILL BE FOREVER GRATEFUL thx

**Comment by ChrisTG742** [comment]
Seems like you have Python 3.9 installed. AFAIK you'll need to upgrade to Python 3.11 for UVR5.
Have a look here: https://www.linuxcapable.com/how-to-install-python-3-11-on-ubuntu-linux/
HTH

**Comment by nananknow** [comment]
thanks for the help, i tried around a bit but still get errors. ive made sure to install the required packages before trying to install python 3.11 and also ran `sudo apt update` afterwards but i still get this error

`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.`

**Comment by joshgura** [comment]
> Seems like you have Python 3.9 installed. AFAIK you'll need to upgrade to Python 3.11 for UVR5. Have a look here: https://www.linuxcapable.com/how-to-install-python-3-11-on-ubuntu-linux/ HTH

i tried installing UVR with python 3.11 and no dice. somebody had a screenshot of it running in a VM on linux with 3.10.12

anyway, it's foolhardy to mess with the system python version since any number of programs may need different versions. the only way to do it properly is with a virtual environment. if UVR can't be run in a virtual environment then the dev needs to remove the word linux from the main page. at any rate it looks like the total number of linux users are vanishingly small. a lot of these new amazing a.i. things are already turning to vaporware and they just came out. that's how fast the tech is going, or how fickle it is. shudder to think what would happen if pypy/pip just wafted away like a fart, or if huggingface sold to adobe for subscribers only...

**Comment by Micraow** [comment]
@joshgura I have the same problem with you. Have you solved it?

**Comment by amateurtools** [comment]
> [@joshgura](https://github.com/joshgura) I have the same problem with you. Have you solved it?

as for myself, it's been a long time since I've needed to install it so I might have forgotten all the details but i had to create a conda env for UVR using conda (or miniconda) . i created an alias ( in ~/aliases.txt ) command to launch it and there's some flags that might have helped.

`alias uvr="conda activate /home/username/opt/UVR/env;__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python3 /home/username/opt/UVR/UVR.py"`

i tried running it just now without the "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia " and it failed to load. so look into setting up nvidia prime if you haven't yet, and try using Python 3.11.10 to set up the conda env. that's the version of python that i'm using and it works. if you're on linux then alter my alias example to comport with your own uvr path, etc.

**Comment by Micraow** [comment]
> > [@joshgura](https://github.com/joshgura) I have the same problem with you. Have you solved it?
> 
> as for myself, it's been a long time since I've needed to install it so I might have forgotten all the details but i had to create a conda env for UVR using conda (or miniconda) . i created an alias ( in ~/aliases.txt ) command to launch it and there's some flags that might have helped.
> 
> `alias uvr="conda activate /home/username/opt/UVR/env;__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia python3 /home/username/opt/UVR/UVR.py"`
> 
> i tried running it just now without the "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia " and it failed to load. so look into setting up nvidia prime if you haven't yet, and try using Python 3.11.10 to set up the conda env. that's the version of python that i'm using and it works. if you're on linux then alter my alias example to comport with your own uvr path, etc.

Thank you for your reply!
Well, I now realize it may not be the same situation. I also use conda and created a python 3.12 virtual environment, but I don't hava an Nvidia card. I am on Intel integrated gpu.

Anyway, thank you again!
